-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.curve("overshotW", { type = "bezier", points = { { 0.15, 0.85 }, { 0.1, 1.03 } } })
hl.curve("overshot", { type = "bezier", points = { { 0.15, 0.85 }, { 0.1, 1.1 } } })
hl.curve("smoothOut", { type = "bezier", points = { { 0.25, 1 }, { 0.5, 1 } } })
hl.curve("smoothIn", { type = "bezier", points = { { 0.25, 1 }, { 0.5, 1 } } })
hl.curve("softSnap", { type = "bezier", points = { { 0.4, 0 }, { 0.2, 1 } } })
hl.curve("fluent", { type = "bezier", points = { { 0.0, 0.0 }, { 0.2, 1.0 } } })
hl.curve("easeInOutExpo", { type = "bezier", points = { { 0.87, 0 }, { 0.13, 1 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 1,
    bezier = "overshot",
    style = "popin 80%",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 2.5,
    bezier = "softSnap",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 1.5,
    bezier = "softSnap",
})
hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 3,
    bezier = "overshotW",
})
hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 4,
    bezier = "smoothIn",
})
hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 5,
    bezier = "softSnap",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 2.5,
    bezier = "smoothIn",
})
hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 2.5,
    bezier = "smoothIn",
})
hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 2.5,
    bezier = "smoothOut",
})
hl.animation({
    leaf = "fadeSwitch",
    enabled = true,
    speed = 2.5,
    bezier = "smoothIn",
})
hl.animation({
    leaf = "fadeShadow",
    enabled = true,
    speed = 2.5,
    bezier = "smoothIn",
})
hl.animation({
    leaf = "fadeDim",
    enabled = true,
    speed = 2.5,
    bezier = "smoothIn",
})
hl.animation({
    leaf = "fadeDpms",
    enabled = true,
    speed = 2.5,
    bezier = "smoothIn",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 2.5,
    bezier = "softSnap",
    style = "slidefadevert",
})
hl.animation({
    leaf = "specialWorkspace",
    enabled = true,
    speed = 3.5,
    bezier = "overshot",
    style = "slidefadevert 30%",
})

hl.config({
    animations = {
        enabled = true,
        -- BEZIER CURVES
        -- We hebben de overshot-curve aangepast (laatste getal naar 1.15) voor een duidelijkere bounce.
        -- Ook is de start-versnelling wat feller gemaakt.
        -- WINDOW MOVEMENTS (Versneld van 5/4 naar 3 deciseconden)
        -- LAYERS (Versneld naar 4 en 5)
        -- FADE ANIMATIONS (Versneld van 4 naar 2.5)
        -- WORKSPACES (Versneld van 5 naar 3.5 voor een snappy gevoel met de nieuwe overshot)
    },
    dwindle = {
        preserve_split = true,
    },
})
