-- Extra autostart processes
-- exec-once = uwsm-app -- my-service
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.on("hyprland.start", function()
    hl.exec_cmd("quickshell")
    hl.exec_cmd("killall waybar")
    hl.exec_cmd("nwg-dock-hyprland -d")
end)

