-- Application bindings
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.bind("SUPER + RETURN", hl.dsp.exec_cmd("uwsm-app -- xdg-terminal-exec --dir=\"$(omarchy-cmd-terminal-cwd)\""), { description = "Terminal" })
hl.bind("SUPER + ALT + RETURN", hl.dsp.exec_cmd("uwsm-app -- xdg-terminal-exec --dir=\"$(omarchy-cmd-terminal-cwd)\" bash -c \"tmux attach || tmux new -s Work\""), { description = "Tmux" })
hl.bind("SUPER + SHIFT + RETURN", hl.dsp.exec_cmd("omarchy-launch-browser"), { description = "Browser" })
hl.bind("SUPER + SHIFT + F", hl.dsp.exec_cmd("uwsm-app -- kitty -e yazi"), { description = "File manager" })
hl.bind("SUPER + ALT + SHIFT + F", hl.dsp.exec_cmd("uwsm-app -- nautilus --new-window \"$(omarchy-cmd-terminal-cwd)\""), { description = "File manager (cwd)" })
hl.bind("SUPER + SHIFT + B", hl.dsp.exec_cmd("omarchy-launch-browser"), { description = "Browser" })
hl.bind("SUPER + SHIFT + ALT + B", hl.dsp.exec_cmd("omarchy-launch-browser --private"), { description = "Browser (private)" })
hl.bind("SUPER + SHIFT + M", hl.dsp.exec_cmd("omarchy-launch-or-focus spotify"), { description = "Music" })
hl.bind("SUPER + SHIFT + ALT + M", hl.dsp.exec_cmd("omarchy-launch-or-focus-tui cliamp"), { description = "Music TUI" })
hl.bind("SUPER + SHIFT + N", hl.dsp.exec_cmd("omarchy-launch-editor"), { description = "Editor" })
hl.bind("SUPER + SHIFT + D", hl.dsp.exec_cmd("omarchy-launch-tui lazydocker"), { description = "Docker" })
hl.bind("SUPER + SHIFT + G", hl.dsp.exec_cmd("omarchy-launch-or-focus ^signal$ \"uwsm-app -- signal-desktop\""), { description = "Signal" })
hl.bind("SUPER + SHIFT + O", hl.dsp.exec_cmd("omarchy-launch-or-focus ^obsidian$ \"uwsm-app -- obsidian\""), { description = "Obsidian" })
hl.bind("SUPER + SHIFT + W", hl.dsp.exec_cmd("uwsm-app -- typora --enable-wayland-ime"), { description = "Typora" })
hl.bind("SUPER + SHIFT + SLASH", hl.dsp.exec_cmd("uwsm-app -- 1password"), { description = "Passwords" })

-- If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
hl.bind("SUPER + SHIFT + E", hl.dsp.exec_cmd("Nautilus"), { description = "nautilus" })
hl.bind("SUPER + SHIFT + Y", hl.dsp.exec_cmd("omarchy-launch-webapp \"https://youtube.com/\""), { description = "YouTube" })

-- Add extra bindings
hl.bind("SUPER + SHIFT + R", hl.dsp.exec_cmd("alacritty -e pkill waybar && waybar &"))
hl.bind("SUPER + C", hl.dsp.exec_cmd(""))

-- TODO: manual review — 'unbind = SUPER, W'. In Lua, capture the result of hl.bind(...) and call :remove(). See hl.meta.lua.
-- TODO: manual review — 'unbind = SUPER SHIFT, F'. In Lua, capture the result of hl.bind(...) and call :remove(). See hl.meta.lua.
-- TODO: manual review — 'unbind = SUPER SHIFT, B'. In Lua, capture the result of hl.bind(...) and call :remove(). See hl.meta.lua.
-- TODO: manual review — 'unbind = SUPER TAB'. In Lua, capture the result of hl.bind(...) and call :remove(). See hl.meta.lua.

-- TODO: manual review on line 36 — no mapping for dispatcher "Killactive"
-- hl.bind("SUPER + C", hl.dsp.Killactive())
hl.bind("SUPER + E", hl.dsp.exec_cmd("kitty yazi"), { description = "File manager" })
hl.bind("SUPER + B", hl.dsp.exec_cmd("zen-browser"))
hl.bind("SUPER + M", hl.dsp.exec_cmd("kitty spotify_player"))
hl.bind("f12", hl.dsp.exec_cmd("rishot"))
-- bind = super, n, exec, nautilus
hl.bind("MOD5 + space", hl.dsp.exec_cmd("fcitx5-remote -t"))

-- Logitech G915 X Volumewiel (via kernel keycodes 114 en 115)
--binde = , code:115, exec, wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+
--binde = , code:114, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
