-- Makes hyprsunset do nothing to the screen by default
-- Without this, the default applies some tint to the monitor
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — unknown section 'profile {' on line 3

-- To enable auto switch to nightlight, set in your .config/hypr/autostart:
-- exec-once = uwsm app -- hyprsunset
-- and use the following:
-- profile {
--     time = 20:00
--     temperature = 4000
-- }
