-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/omarchy/current/theme/hyprlock.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprlock")

-- TODO: manual review — unknown section 'background {' on line 8

-- TODO: manual review — unknown section 'label {' on line 16

-- TODO: manual review — unknown section 'label {' on line 26

-- TODO: manual review — unknown section 'image {' on line 38

-- TODO: manual review — unknown section 'input-field {' on line 48

-- TODO: manual review — unknown section 'label {' on line 69
hl.config({
    animations = {
        enabled = false,
    },
})

