-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — unknown section 'listener {' on line 9

-- TODO: manual review — unknown section 'listener {' on line 15
hl.config({
    general = {
        lock_cmd = "omarchy-system-lock", -- lock screen and 1password
        before_sleep_cmd = "OMARCHY_LOCK_ONLY=true omarchy-system-lock", -- lock before suspend without scheduling display off.
        after_sleep_cmd = "sleep 1 && omarchy-system-wake", -- delay for PAM readiness, then turn on display.
        inhibit_sleep = 3, -- wait until screen is locked
    },
    -- Start screensaver after 2.5 minutes
    -- Lock system after 5 minutes (screensaver resets idle timer, so have to just do half + 2s margin)
})

