-- Learn how to configure Hyprland: https://wiki.hypr.land/Configuring/

-- Use defaults Omarchy defaults (but don't edit these directly!)
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- hyprlang2lua polyfills — runtime helpers reproducing
-- hyprlang behaviour the typed Lua API doesn't expose directly.

local function hl_source_glob(pattern)
    -- 'source = path/*.conf' had hyprlang glob and inline-expand the
    -- matches. require() can't glob, so we shell out to ls (matching
    -- the user's brace-expansion behaviour) and dofile each result.
    -- Paths with spaces or shell metacharacters in the directory
    -- portion will misparse; typical ~/.config/hypr/ layouts don't
    -- hit this. Swap to lfs.dir() or find -name if you need fancier.
    local p = io.popen("ls " .. pattern .. " 2>/dev/null")
    if not p then return end
    for f in p:lines() do
        local chunk, err = loadfile(f)
        if chunk then chunk()
        else io.stderr:write("hl_source_glob: " .. tostring(err) .. "\n") end
    end
    p:close()
end

-- Source: ~/.local/share/omarchy/default/hypr/autostart.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("autostart")
-- Source: ~/.local/share/omarchy/default/hypr/bindings/media.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("bindings.media")
-- Source: ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("bindings.clipboard")
-- Source: ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("bindings.tiling-v2")
-- Source: ~/.local/share/omarchy/default/hypr/bindings/utilities.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("bindings.utilities")
-- Source: ~/.local/share/omarchy/default/hypr/envs.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("envs")
-- Source: ~/.local/share/omarchy/default/hypr/looknfeel.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("looknfeel")
-- Source: ~/.local/share/omarchy/default/hypr/input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("input")
-- Source: ~/.local/share/omarchy/default/hypr/windows.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("windows")
-- Source: ~/.config/omarchy/current/theme/hyprland.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland")

-- Change your own setup in these files (and overwrite any settings from defaults!)
-- Source: ~/.config/hypr/monitors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("monitors")
-- Source: ~/.config/hypr/input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("input")
-- Source: ~/.config/hypr/bindings.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("bindings")
-- Source: ~/.config/hypr/looknfeel.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("looknfeel")
-- Source: ~/.config/hypr/autostart.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("autostart")
-- Source: ~/.config/hypr/animations.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("animations")

-- source = ~/.config/hypr/hypridle.conf

-- Toggle config flags dynamically
-- Source: ~/.local/state/omarchy/toggles/hypr/*.conf (glob; resolved at runtime). Each matched .conf must be converted to .lua.
hl_source_glob("~/.local/state/omarchy/toggles/hypr/*.lua")

-- Add any other personal Hyprland configuration below
-- windowrule = workspace 5, match:class qemu

hl.env("XCURSOR_THEME", "macOS-White")
hl.env("XCURSOR_SIZE", "32")
hl.env("HYPRCURSOR_THEME", "macOS-White")
hl.env("HYPRCURSOR_SIZE", "32")
hl.env("QT_IM_MODULE", "fcitx")
hl.env("XMODIFIERS", "@im=fcitx")
hl.env("QS_ICON_THEME", "MacTahoe-dark")

hl.layer_rule({
    match = { namespace = "match:namespace walker" },
    -- TODO: manual review — unmapped layer rule: "blur true"
    -- TODO: manual review — unmapped layer rule: "no_anim true"
})

hl.layer_rule({
    match = { namespace = "match:namespace logout_dialog" },
    -- TODO: manual review — unmapped layer rule: "blur true"
})

hl.layer_rule({
    match = { namespace = "match:namespace quickshell" },
    -- TODO: manual review — unmapped layer rule: "blur true"
})

hl.layer_rule({
    match = { namespace = "match:namespace hyprdock" },
    -- TODO: manual review — unmapped layer rule: "blur true"
})

hl.window_rule({
    match = {
        class = "^hyprland-display-streamer$",
    },
    float = true,
})

hl.window_rule({
    match = {
        focus = false,
    },
    border_size = 0,
    no_shadow = true,
})

hl.config({
    decoration = {
        blur = {
            enabled = true,
            size = 4,
            passes = 2,
            noise = 0.0,
            contrast = 1,
            brightness = 0.9,
        },
    },
    -- layers
    -- windows
})

hl.on("hyprland.start", function()
    hl.exec_cmd("fcitx5 -d")
    hl.exec_cmd("hyprctl setcursor macOS-White 32")
    hl.exec_cmd("hd -n")
end)

