-- Generated by nwg-displays on 2026-08-07 at 12:34:48. Do not edit manually.

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@144.0",
    position = "5238x1368",
    scale = "1.0",
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "3840x2160@60.0",
    position = "2166x720",
    scale = "1.25",
})

