# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" bash -c "tmux attach || tmux new -s Work"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- kitty -e yazi
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT ALT, M, Music TUI, exec, omarchy-launch-or-focus-tui cliamp
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian"
bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password


# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, E, nautilus, exec, Nautilus
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"


# Add extra bindings
bind = SUPER SHIFT, R, exec, alacritty -e pkill waybar && waybar &
bind = SUPER , C, exec,

unbind = SUPER, W
unbind = SUPER SHIFT, F
unbind = SUPER SHIFT, B
unbind = SUPER TAB
unbind = SUPER, SPACE



bind = SUPER, C, Killactive
bindd = SUPER, E, File manager, exec, kitty yazi
bind = SUPER, B, exec, zen-browser
bind = SUPER, M, exec, kitty spotify_player
bind = , f12, exec, rishot
# bind = super, n, exec, nautilus
bind = MOD5, space, exec, fcitx5-remote -t
bind = super, space, exec, rofi -show drun -theme ~/.config/rofi/launchpad.rasi
bind = super shift, c, exec, walker -m calc


# Logitech G915 X Volumewiel (via kernel keycodes 114 en 115)
#binde = , code:115, exec, wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+
#binde = , code:114, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
