# Learn how to configure Hyprland: https://wiki.hypr.land/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/animations.conf

# source = ~/.config/hypr/hypridle.conf


# Toggle config flags dynamically
source = ~/.local/state/omarchy/toggles/hypr/*.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu

env = XCURSOR_THEME,macOS-White
env = XCURSOR_SIZE,32
env = HYPRCURSOR_THEME,macOS-White
env = HYPRCURSOR_SIZE,32
env = QT_IM_MODULE, fcitx
env = XMODIFIERS, @im=fcitx

exec-once = fcitx5 -d
exec-once = hyprctl setcursor macOS-White 32

plugin {
    hyprglass {
        enabled = true
        default_theme = dark

        # Rustige, strakke instellingen:
        blur_strength = 1
        refraction_strength = 1.5
        chromatic_aberration = 1.5    # Bijna geen drukke kleurscheiding
        edge_thickness = 0.1          # Subtiele glasrand
        tint_color = 0xccccff11        # Lichte donkere tint
        specular_strength = 0.3       # Zachte lichtreflectie
    }
}

decoration {
    blur {
        enabled = true
        size = 8
        passes = 2
        noise = 0.03
        contrast = 0.5
        brightness = 1.1
   }
}


# layers
layerrule = blur true, match:namespace walker
layerrule = no_anim true, match:namespace walker
layerrule = blur true, match:namespace logout_dialog
layerrule = blur true, match:namespace quickshell, ignore_alpha 0.1

# windows
windowrule = float true, match:class ^hyprland-display-streamer$
windowrule = match:focus false, border_size 0, no_shadow true
